title: Gib einem großen Sprachmodell eine Eingabeaufforderung
hero_image: images/banner.png
description: Folge dem OCEAN-Eingabeprozess, um zuverlässige, klare Eingabeaufforderungen zu erstellen, die dir jedes Mal die gewünschten Ergebnisse von einem LLM liefern!
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Einleitung
  - 
    title: Gib einem GSM eine Eingabeaufforderung
    completion:
      - engaged
  - 
    title: Lege eine Rolle für ein LLM fest
    completion:
      - external
