title: Prompt a large language model
hero_image: images/banner.png
description: Follow the OCEAN prompting process to create reliable, clear prompts that get what you want from an LLM every time!
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Einleitung
  - 
    title: Prompt an LLM
    completion:
      - engaged
  - 
    title: Set a persona for an LLM
    completion:
      - internal
  - 
    title: Was kannst du jetzt tun?
    completion:
      - external
