title: Escreva um prompt para um grande modelo de linguagem
hero_image: images/banner.png
description: Siga o processo OCEAN de criação de prompt para criar prompts confiáveis e claros que sempre lhe darão o que você quer de um LLM!
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Introdução
  - 
    title: Escreva um prompt para um LLM
    completion:
      - engaged
  - 
    title: Defina uma persona para um LLM
    completion:
      - internal
  - 
    title: O que você pode fazer agora?
    completion:
      - external
