title: Dale una instrucción a un modelo de lenguaje grande
hero_image: images/banner.png
description: '¡Sigue el proceso de prompting OCEAN para crear instrucciones claras y fiables que consigan lo que quieres del LLM en todo momento!'
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Introducción
  - 
    title: Dale una instrucción a un LLM
    completion:
      - engaged
  - 
    title: Configura una personalidad para un LLM
    completion:
      - external
