title: Daj polecenie dużemu modelowi językowemu (LLM)
hero_image: images/banner.png
description: Postępuj zgodnie z procesem OCEAN, aby dawać niezawodne, jasne polecenia, dzięki którym za każdym razem otrzymasz to, czego chcesz od LLM-a!
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Wprowadzenie
  - 
    title: Daj polecenie LLM-owi
    completion:
      - engaged
  - 
    title: Ustaw osobowość LLM-a
    completion:
      - internal
  - 
    title: Co możesz teraz zrobić?
    completion:
      - external
