title: Suggerisci un modello linguistico di grandi dimensioni
hero_image: images/banner.png
description: Segui il processo suuggerito detto OCEAN per creare prompt affidabili e chiari che ti consentano di ottenere ogni volta ciò che desideri da un LLM!
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Introduzione
  - 
    title: Sollecita un LLM
    completion:
      - engaged
  - 
    title: Imposta una persona per un LLM
    completion:
      - internal
  - 
    title: Cosa puoi fare adesso?
    completion:
      - external
