---
title: Scrivi un prompt per un modello linguistico di grandi dimensioni
hero_image: images/banner.png
description: Segui il processo OCEAN per creare prompt chiari e affidabili, e ottenere sempre ciò che desideri da un modello linguistico di grandi dimensioni!
version: 4
listed: true
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Introduzione
  - title: Fornisci un prompt a un modello linguistico di grandi dimensioni
    completion:
      - engaged
  - title: Imposta un ruolo per il modello linguistico di grandi dimensioni
    completion:
      - internal
    completion:
      - external
